"""Add description, themes, fun_facts, and quote to Episode

Revision ID: f043d6f54f8f
Revises: 425a733556cc
Create Date: 2025-04-08 16:57:11.614881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f043d6f54f8f'
down_revision = '425a733556cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('themes', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fun_facts', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quote', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_column('quote')
        batch_op.drop_column('fun_facts')
        batch_op.drop_column('themes')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
